### PR TITLE
Resolve alpha bugs for import feature

### LINKED ISSUE #124: [Feature Flaw] Misleading example for import command
Image

The example shows "import addressbook.csv" however, this might be confusing for users who are not familiar with filepaths. As mentioned in the description of the command, perhaps the example could be changed to "import ./exports/addressbook.csv" to ensure that it is clearer for the user to use the command.

### PR DESCRIPTION
**Pull request by Parrycys**
Fixes #124 #120 #121 #112 #110 #109

### CODE REVIEW

**Comment by GCheeYang** [comment]
Maybe error messages for importing vcf and csv could be stanrdadized to 'contact X' instead of 'row X' for csv/vcf documents?

**Review by GCheeYang — COMMENTED** [review]
Maybe error messages for importing vcf and csv could be stanrdadized to 'contact X' instead of 'row X' for csv/vcf documents?

**Comment by Parrycys** [comment]
I keep it as it is where row is used for CSV and contact is used for VCF so that there is a clear distinction. Furthermore, since CSV has row numbers while VCF does not, it is easier to differentiate between the two.

File: src/test/java/seedu/address/model/person/PersonTest.java [hunk 1]
```diff
@@ -38,20 +38,20 @@ public void isSamePerson() {
         // same name, all other attributes different -> returns true
         Person editedAlice = new PersonBuilder(ALICE).withPhone(VALID_PHONE_BOB).withEmail(VALID_EMAIL_BOB)
                 .withAddress(VALID_ADDRESS_BOB).withRole(VALID_ROLE_BOB).withTags(VALID_TAG_HUSBAND).build();
-        assertTrue(ALICE.isSamePerson(editedAlice));
+        assertFalse(ALICE.isSamePerson(editedAlice));
```
Comment (sherwinee) [inline src/test/java/seedu/address/model/person/PersonTest.java:41]: Nice use of assertions to aid with defensive coding!

**Review by sherwinee — COMMENTED** [review]
LGTM
